### ISSUE TITLE
Use CI to generate the html files, remove them from the repo

### ISSUE THREAD

**Issue by certik** [sympy/sympy.github.com#102]
The repository should only hold the sources, and all generated files should be handled by a CI.

**Comment by bjodah** [comment]
I guess Travis + Aaron's doctr would be a good match. Should the sources be in this repo under another branch, or should there be a separate repo holding the sources (and have the CI job of that repo push to this repo?)

**Comment by certik** [comment]
I think the master of this repo is what is used for the webpage, isn't it? So I think we should probably create a new repository and just push here, to avoid confusion where PRs should be sent.

**Comment by asmeurer** [comment]
We could use a different branch (GitHub lets you change the default branch). I also like the idea of having a separate `website` repo.

**Comment by asmeurer** [comment]
I am working on this. I have created a new `sources` branch, which is the default branch. I am setting up Travis with doctr to build and deploy it to the master branch, which should no longer be pushed to manually. 

Currently I have it set so that all files are synced. We might want to update it so that everything is built into a `build` directory and only those files are synced.

**Comment by certik** [comment]
Thank you Aaron. Much appreciated.

**Comment by asmeurer** [comment]
Running into some doctr bugs. Should get things going once I get a doctr release out with the fix.

**Comment by asmeurer** [comment]
OK, I have the deploy working. I had to remove the submodule from the sources directory, meaning you won't be able to properly view the changes on your own system. I hope to get it added back in once I figure out how to make it work properly with doctr.

**Comment by asmeurer** [comment]
Alright, the `static` submodule is now back in the main `sources` branch. 

I added some text to the [README](https://github.com/sympy/sympy.github.com/blob/sources/README.md) on how to update the files and view them. This can be closed now. All existing and new pull requests should be made against the `sources` branch. I'm going to enable branch protection as well, so that people cannot push to `sources` directly (Travis has to pass). Unfortunately, I can't do the same for `master` or it would break the deploy.
