### ISSUE TITLE
Site not found

### ISSUE THREAD

**Issue by kripnerl** [sympy/sympy.github.com#142]
https://www.sympy.org/

returns

There isn't a GitHub Pages site here.

**Comment by certik** [comment]
Wow, you are right!

@asmeurer I wasn't touching any configuration lately. Did you make any changes?

**Comment by certik** [comment]
This is our current configuration of this repository:

![Screenshot from 2020-08-04 09-32-55](https://user-images.githubusercontent.com/20568/89313320-93d45b80-d635-11ea-9d4e-51776089439d.png)

I don't see any problem there.

**Comment by certik** [comment]
I also checked the sympy.org DNS, which points to Linode nameservers, and there `www.sympy.org` points to `sympy.github.io`, and GitHub should serve it correctly. 

Could this be a problem at GitHub?

**Comment by isuruf** [comment]
@certik, shouldn't the branch be `master` instead of `sources`?

**Comment by certik** [comment]
I don't know -- I can see this repository has both branches.

**Comment by certik** [comment]
I switched it to master and it seems to work! Good catch.

How did that happen?

**Comment by Sc0rpi0n101** [comment]
Yeah, Travis is deploying from the source branch into the master branch.
So, I think it should be the master branch.

**Comment by isuruf** [comment]
Github previously used `master` as the branch to serve the pages from. We had `sources` as the default branch because that's where contributors have to send changes to. Github recently added a feature to select the branch and it defaulted to the default branch which is `sources`, but the website still worked because there were no new commits in `sources` branch. The PR merged yesterday triggered a website build and github selected `sources`.

**Comment by certik** [comment]
@isuruf ah, that explains it. Thank you! Thanks @Sc0rpi0n101 also.

For reference, here is the correct setting:

![Screenshot from 2020-08-04 09-59-39](https://user-images.githubusercontent.com/20568/89316409-4e199200-d639-11ea-9f06-5f9c87eac05f.png)

**Comment by asmeurer** [comment]
Looks like GitHub messed up their implementation of this feature. 

By the way, now that we can serve the pages from any branch, we should make it so that `master` is the default branch with the sources and `gh-pages` is the branch with the served pages. This will be much less confusing to contributors.

**Comment by asmeurer** [comment]
Or maybe stick with `sources` for the default branch and remove `master` entirely, to avoid confusion from people who expect `master` to be the GitHub pages branch on .github.com repos.

**Comment by certik** [comment]
First let's move the serving of the pages from `master` to `gh-pages`.

Then we can talk about moving `sources` to `master`.
